### ISSUE TITLE
guys help i ran the code and now my windows turned into a mac ?????

### ISSUE THREAD

**Issue by Applehihi** [Fishboii/squabbling#1]
wtf i am running out of oxygen the window is gone 

> be me
> download file
> run liscence.html
> ???
> wtf
@Fishboii 
[this is what happened](www.example.com) 

- [ ] i am going to fork
- [ ] i have read community guideines (epicsauce (that is the secret codeword))

**Comment by Applehihi** [comment]
> wtf i am running out of oxygen the window is gone
> 
> > be me
> > download file
> > run liscence.html
> > ???
> > wtf
> > @Fishboii
> > [this is what happened](www.example.com)
> 
> * [ ]  i am going to fork
> * [ ]  i have read community guideines (epicsauce (that is the secret codeword))

how do i put a label

**Comment by Fishboii** [comment]
next time run it better
